database_config:
  database_type: mongodb 
  sqlite_database:
    db_file: db/local_database.sqlite
    timeout: 5000  
    pool_size: 5   
  mongodb:
    uri: "mongodb+srv://berdnykoleksandr:0h5oLsT3NFcqS5I5@cluster0.9zitoit.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    db_name: "my_database"