web_scraping:
  # URL початкової сторінки для збору даних
  start_page: https://www.yakaboo.ua/ua/knigi/business-money-economy.html
  
  # CSS селектор для отримання назв продуктів
  product_name_selector: ".category-card__name"
  
  # CSS селектор для отримання цін продуктів
  product_price_selector: ".product-price"
  
  # CSS селектор для отримання опису продуктів
  product_description_selector: ".description__content"
  
  # CSS селектор для отримання зображень продуктів
  product_image_selector: ".slide__img"
